sudo: required 
services:
    - docker 

before_install: 
    - docker build -t qalqahtani/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true qalqahtani/docker-react npm  run test -- --coverage 

deploy: 
    provider: elasticbeanstalk
    regoin: "me-south-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-me-south-1-066329270393"
    bucket_path: "docker"
    on:
        branch: master 
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY