sudo: required 
services:
    - docker 

before_install: 
    - docker build -t qalqahtani/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true qalqahtani/docker-react npm  run test -- --coverage 